### PR TITLE
Upgraded HPPC to version 0.7.1

### PR DESCRIPTION
**Pull request by mcelvg**
This is an upgrade to HPPC version 0.7.1 for compatibility with projects that depend on [carrot2 >= 3.10.0](http://mvnrepository.com/artifact/org.carrot2/carrot2/3.10.0).

Relevant API-breaking changes:
- [HPPC-145](http://issues.carrot2.org/browse/HPPC-145): Removed any "Open" infix from all classes.
- [HPPC-97](http://issues.carrot2.org/browse/HPPC-97): Use unallocated slot marker key instead of an explicit allocation table for hash containers.

see [hppc/changes.txt](https://github.com/carrotsearch/hppc/blob/master/CHANGES.txt)

### CODE REVIEW

**Comment by jdchoi77** [comment]
I’ll take a look at this upgrade.  Thanks.

best,

Jinho D. Choi
Assistant Professor of Math and Computer Science
Emory University

400 Dowman Dr, Atlanta, GA 30322
Tel: (404) 712-5694, Fax: (404) 727-5611
http://www.mathcs.emory.edu/~choi

On Jul 15, 2015, at 12:10 AM, mcelvg <notifications@github.com<mailto:notifications@github.com>> wrote:


Upgrading to HPPC version 0.7.1 for compatibility with projects that depend on carrot2 >= 3.10.0<http://mvnrepository.com/artifact/org.carrot2/carrot2/3.10.0>.

Relevant API-breaking changes:

  *   HPPC-145<http://issues.carrot2.org/browse/HPPC-145>: Removed any "Open" infix from all classes.
  *   HPPC-97<http://issues.carrot2.org/browse/HPPC-97>: Use unallocated slot marker key instead of an explicit allocation table for hash containers.

see hppc/changes.txt<https://github.com/carrotsearch/hppc/blob/master/CHANGES.txt>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/clir/clearnlp/pull/5

Commit Summary

  *   Upgraded HPPC to version 0.7.1

File Changes

  *   M pom.xml<https://github.com/clir/clearnlp/pull/5/files#diff-0> (2)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/CharCharHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-1> (36)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/CharIntHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-2> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/CharObjectHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-3> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/IntDoubleHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-4> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/IntIntHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-5> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/IntObjectHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-6> (40)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/ObjectDoubleHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-7> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/map/ObjectIntHashMap.java<https://github.com/clir/clearnlp/pull/5/files#diff-8> (38)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/set/CharHashSet.java<https://github.com/clir/clearnlp/pull/5/files#diff-9> (10)
  *   M src/main/java/edu/emory/clir/clearnlp/collection/set/IntHashSet.java<https://github.com/clir/clearnlp/pull/5/files#diff-10> (10)
  *   M src/main/java/edu/emory/clir/clearnlp/constituent/CTTree.java<https://github.com/clir/clearnlp/pull/5/files#diff-11> (6)
  *   M src/test/java/edu/emory/clir/clearnlp/collection/map/ObjectDoubleHashMapTest.java<https://github.com/clir/clearnlp/pull/5/files#diff-12> (5)
  *   M src/test/java/edu/emory/clir/clearnlp/collection/map/ObjectIntHashMapTest.java<https://github.com/clir/clearnlp/pull/5/files#diff-13> (7)

Patch Links:

  *   https://github.com/clir/clearnlp/pull/5.patch
  *   https://github.com/clir/clearnlp/pull/5.diff

—
Reply to this email directly or view it on GitHub<https://github.com/clir/clearnlp/pull/5>.


________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by ColinArenz** [comment]
Is this pull still being evaluated?  We're investigating updating [OpenIE](https://github.com/allenai/openie-standalone) to this version to resolve a dependency conflict.

**Comment by jdchoi77** [comment]
I just merged the pull request.  By the way, the ClearNLP project is officially moved to the NLP4J project where these changes are already made so you may want to take a look:

https://github.com/emorynlp/nlp4j

It will most likely that ClearNLP will not get any further update.  Please let me know if you have any question migrating.  Thanks.

**Comment by ckarenz** [comment]
Thanks!  We're moving forward to this version in the short term as it's an easy transition from the older com.clearnlp package.  Moving to NLP4J appears non-trivial, but I'd like to move in that direction in the longer term.

**Comment by jdchoi77** [comment]
Thanks, please let me know if you have any question/comment.

**Pull request merged**
